# server
host: "0.0.0.0"
httpPort: "8182"
grpcPort: "8185"

# logger
logLevel: "debug"

# storage
inmemStore: false

postgresDsn: "host=db-calendar port=5432 user=postgres password=postgres dbname=calendar sslmode=disable"

