# server
host: "127.0.0.1"
httpPort: "8182"
grpcPort: "8185"

# logger
logLevel: "debug"

# storage
inmemStore: false

postgresDsn: "host=127.0.0.1 port=5436 user=postgres password=postgres dbname=calendar sslmode=disable"

