#rmq
user: user
password: pass
host: "127.0.0.1"
port: "5672"

# logger
logLevel: "debug"

# storage
postgresDsn: "host=127.0.0.1 port=5436 user=postgres password=postgres dbname=calendar sslmode=disable"

# years
storagePeriod: 1
# mins
removeScannerFrequency: 60
notifyScannerFrequency: 1
