version: '3.8'

services:
  db-calendar:
    container_name: calendar-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "host=127.0.0.1 port=5436 user=postgres password=postgres dbname=calendar sslmode=disable"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar
    ports:
      - "5436:5432"