version: '3.8'

services:
  db-calendar:
    container_name: calendar-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar
    ports:
      - "5432:5432"
    networks:
      some_network:
        aliases:
          - testdb.local

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      some_network:

  calendar:
    image: calendar:latest
    container_name: calendar-app
    restart: always
    ports:
      - "127.0.0.1:8182:8182"
      - "8185:8185"
    depends_on:
      - db-calendar
    hostname: calendar-app
    networks:
      some_network:
        aliases:
          - calendar.service

  scheduler:
    image: scheduler:latest
    container_name: scheduler-app
    restart: always
    depends_on:
      - db-calendar
      - rabbitmq
    networks:
      some_network:

  sender:
    image: sender:latest
    container_name: sender-app
    restart: always
    depends_on:
      - rabbitmq
      - scheduler
    networks:
      some_network:

networks:
  some_network:
    name: 'our_network'